"""empty message

Revision ID: 761cebd42280
Revises: 
Create Date: 2017-06-26 21:01:46.901692

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '761cebd42280'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'users', ['username'])
    op.create_unique_constraint(None, 'users', ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'users', type_='unique')
    # ### end Alembic commands ###
